CREATE TABLE Autor(
IDAutor	VARCHAR(50) NOT NULL,
SobrenomeAutor VARCHAR(60) NOT NULL,
CONSTRAINT pk_id_autor PRIMARY KEY (idAutor)
);
Sp_help Autor:

CREATE TABLE Editora(
IDEditora SMALLINT PRIMARY KEY IDENTITY,
NomeEditora VARCHAR(50) NOT NULL,
);
CREATE TABLE Assunto(
IDAssunto TINYINT PRIMARY KEY IDENTITY,
NomeAssunto VARCHAR(25) NOT NULL,
);
CREATE TABLE Livro(
IDLivro SMALLINT PRIMARY KEY IDENTITY(100,1),
NomeLivro VARCHAR(70) NOT NULL,
ISBN13 CHAR(13) UNIQUE NOT NULL,
DataPub DATE,
PreçoLivro MONEY NOT NULL,
NumeroPaginas SMALLINT NOT NULL,
IDEditora SMALLINT NOT NULL,
IDAssunto TINYINT NOT NULL,
CONSTRAINT fk_id_editora FOREIGN KEY (IDEditora) REFERENCES Editora (IDeditora) ON DELETE CASCADE,
CONSTRAINT fk_id_assunto FOREIGN KEY (IDAssunto) REFERENCES Assunto (IDAssunto) ON DELETE CASCADE,
CONSTRAINT verificar_preco CHECK (PreçoLivro >=0)
);
CREATE TABLE LivroAutor(
IDLivro SMALLINT NOT NULL,
IDAutor INT NOT NULL,
CONSTRAINT fk_id_livros FOREIGN KEY (IDLivro) REFERENCES Livro (IDLivro),
CONSTRAINT fk_id_autores FOREIGN KEY (IDAutor) REFERENCES Autor (IDAutor),
CONSTRAINT pk_id_livro_autor PRIMARY KEY (IDLivro, IDAutor)
);
GO
